spring:
  cloud:
    stream:
      defaultBinder: rabbit
  config:
    activate:
      on-profile: cloud-bus-rabbit
---
spring:
  cloud:
    stream:
      defaultBinder: kafka
  config:
    activate:
      on-profile: cloud-bus-kafka
---
spring:
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          basedir: /config-git-base
          default-label: master
  config:
    activate:
      on-profile: git
