name: Build docker image

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  REPO: docker.pkg.github.com/vimukthi-hms/spring-cloud-config-server
  REGISTRY: docker.pkg.github.com
  REPOSITORY: spring-cloud-config-server
  BUILD_IMAGE_NAME: spring-cloud-config-server

jobs:
  docker-build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        include:
          - module: spring-cloud-config-server
            MODULE_DIR: .
            IMAGE_NAME: spring-cloud-config-server

    steps:
      - uses: actions/checkout@v2
      - name: Log into registry
        run: echo "${{ secrets.PACKAGE_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: Run docker build and push to GitHub Repo
        id: docker_build
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: ${{ env.REPOSITORY }}/${{ matrix.IMAGE_NAME }}
          tag: latest
          registry: ${{ env.REGISTRY }}
          dockerfile: ${{ matrix.MODULE_DIR }}/Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGE_TOKEN }}
          buildArgs: SPRING_CLOUD_CONFIG_SERVER_GIT_URI=${{ secrets.CONFIG_URL }},SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME=${{ secrets.CONFIG_USER }},SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD=${{ secrets.CONFIG_TOKEN }},SPRING_PROFILES_ACTIVE="git"
          directory: ${{ matrix.MODULE_DIR }}